spring:
  application:
    name: opendemo-user-registration-service
server:
  port: ${SERVER_PORT}
  shutdown: graceful
  servlet:
    context-path: /user-registration-ms
logging:
  level:
    root: info
    web: info
